# Stock Market Prediction

In [1]:
import pandas as pd
import numpy as np
import sklearn

In [2]:
df = pd.read_csv('stock.csv')

In [3]:
df.tail()

Date        Open        High         Low       Close   Adj_Close  \
4387  2017/9/1  113.790001  114.099998  112.790001  113.309998  113.309998   
4388  2017/9/5  112.519997  113.529999  111.160004  111.870003  111.870003   
4389  2017/9/6  112.029999  112.489998  110.250000  112.230003  112.230003   
4390  2017/9/7  112.459999  112.900002  112.000000  112.339996  112.339996   
4391  2017/9/8  112.300003  114.790001  112.010002  113.190002  113.190002   

       Volume  
4387   950000  
4388  1805200  
4389  2136700  
4390  1251600  
4391  1611700

In [4]:
X=df.iloc[:,[1,2,3]].values
X

array([[  3.8125  ,   4.15625 ,   3.8125  ],
       [  4.125   ,   4.125   ,   4.      ],
       [  4.      ,   4.03125 ,   3.953125],
       ...,
       [112.029999, 112.489998, 110.25    ],
       [112.459999, 112.900002, 112.      ],
       [112.300003, 114.790001, 112.010002]])

In [14]:
y=df.iloc[:,4].values

In [15]:
y

array([  4.125   ,   4.015625,   4.      , ..., 112.230003, 112.339996,
       113.190002])

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
X_train,X_test,y_train,y_test =train_test_split(X,y,test_size=0.2,random_state=0)

In [18]:
from sklearn.linear_model import LinearRegression

In [19]:
regressor = LinearRegression()

In [20]:
regressor.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [21]:
Z=[[113.79008,114.09998,112.79002]]
y_pred = regressor.predict(Z)

In [22]:
y_pred

array([113.23337748])